robertknight/ocrs

Cargo.lock, ocrs-cli/Cargo.toml, ocrs-cli/src/models.rs
`ocrs` currently relies on checking the `HOME` environment variable to determine where to placed cached models. Windows doesn't use this, though, so of course, it breaks. 😅
Implement the proper cross-platform logic for getting a home directory with [`home::home_dir`].
`ocrs`' current dependency tree use `windows` 0.48.0 because of the `ring` dependency via dependency on `ureq`. This PR unfortuantely also brings in `windows` 0.52.0 as a duplicate dependency. [`briansmith/ring`#1852] upgrades `ring` to use `windows` 0.52.0, and should be followed up with to remove this dep. duplication.
[`briansmith/ring`#1852]: https://github.com/briansmith/ring/pull/1852
[`home::home_dir`]: https://docs.rs/home/0.5.9/home/fn.home_dir.html
=> fix(windows): use `home::home_dir` instead of `HOME` env. var

LICENSE-APACHE.txt, LICENSE-MIT.txt
These were copied from https://github.com/rust-lang/rust and a copyright notice was added to the MIT license.
Per recommendations from
https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive, the crates and other supporting materials are all "MIT or Apache 2.0" licensed.
Fixes https://github.com/robertknight/ocrs/issues/11
=> Add license files to root of repository

ocrs-cli/src/main.rs, ocrs-cli/src/output.rs, ocrs/src/detection.rs, ocrs/src/layout_analysis.rs, ocrs/src/layout_analysis/empty_rects.rs, ocrs/src/lib.rs, ocrs/src/preprocess.rs, ocrs/src/recognition.rs, ocrs/src/test_util.rs
I just used `cargo clippy -- -Wclippy::pedantic` to take a look into some potential fixes.
Some are straightforward and obvious, but some are more opinionated.
Let me know what you think!
=> Apply fixes from `-Wclippy::pedantic`

ocrs/src/layout_analysis.rs
Word detection can produce words which have a small overlap. This is because the detection model predicts boxes which are slightly shrunk from their true size, and post-processing then pads the boxes to recover the "true" size.
This means it is possible for the average inter-word spacing in a line to be negative. When this happens a panic occurred when converting the spacing from signed to unsigned.
The fix is just to clamp the computed average spacing to be >= 0.
Fixes https://github.com/robertknight/ocrs/issues/19
=> Fix panic in layout analysis when average word spacing in a line is negative

Cargo.lock, ocrs-cli/Cargo.toml, ocrs-cli/src/output.rs, ocrs/Cargo.toml, ocrs/examples/hello_ocr.rs, ocrs/src/detection.rs, ocrs/src/lib.rs, ocrs/src/wasm_api.rs
Adapt to rten unified tensor changes:
- The `view` function is now part of the prelude
- The `slice` method has now been split into two, depending on whether a static or dynamic-rank result is required
- `NdTensor::from_data` now has the same signature as `Tensor::from_data`
=> Update to rten v0.3

ocrs-cli/src/main.rs, ocrs/src/detection.rs, ocrs/src/lib.rs
Add `--text-map` option to ocrs CLI tool and supporting `OcrEngine::detect_text_pixels` API to generate a text probability mask.
This is useful for debugging text detection differences between model versions.
In the process a `params` argument was added to `TextDetector::from_model` to make it easier to test adjustments to various post-processing parameters.
=> Add API and CLI option for generating text segmentation mask

Cargo.lock, ocrs-cli/Cargo.toml, ocrs/Cargo.toml
This brings optimization to `find_contours` plus support for additional `AveragePool` operator attributes, needed to use text recognition models exported from the newest PyTorch releases.
=> Bump rten to v0.4.0

Cargo.lock, Makefile, ocrs-cli/Cargo.toml, ocrs-cli/src/main.rs, ocrs-cli/src/models.rs, ocrs-cli/test-data/why-rust.expected.txt
Make `make test-e2e` actually check the text produced against expectations.
In the process of debugging a CI failure, the error messages produced when writing the output file fails have also been improved.
=> Actually check E2E test output, add more context to output errors

ocrs/README.md
Debug builds, especially of the `rten*` crates, are an order of magnitude or more slower.
This was prompted by https://github.com/robertknight/ocrs/issues/7 and https://github.com/robertknight/ocrs/issues/15#issuecomment-1954170017.
=> Add stronger hint to users to build `ocrs` and `rten*` crates in release mode

Makefile, tools/test-e2e.py
This enables adding new test cases just by adding new images + expected text output in `ocrs-cli/test-data/`.
=> Add Python script to run end-to-end tests

Cargo.lock, ocrs-cli/Cargo.toml, ocrs/Cargo.toml
Amongst other changes, this includes an update to `rten::Model` which makes it usable in a PyO3 class.
=> Update to rten v0.5.0

.github/workflows/ci.yml, ocrs-cli/src/main.rs, ocrs/Cargo.toml, ocrs/src/detection.rs, ocrs/src/lib.rs
This saves the binarized version of the text probability map as a PNG file. This
is useful to see where detections were above/below the current confidence
threshold.
Input image:
Probability map (`text-map.png`, generated by `--text-map`):
Binary mask (`text-mask.png`, generated by `--text-mask`):
=> Add `--text-mask` flag to CLI tool

.github/workflows/ci.yml, Makefile, ocrs-cli/Cargo.toml
When running `cargo doc` the docs for the `ocrs` binary would end up overwriting the docs for the `ocrs` library crate in `target/doc/ocrs`. Only the docs for the library crate are actually useful, so disable doc generation for the binary using `doc = false`. This follows suggestions in https://github.com/rust-lang/cargo/issues/6313.
Also generate docs in CI.
=> Disable doc generation for ocrs CLI tool

Makefile, ocrs/examples/hello_ocr.rs
- Improve some comments about what the steps in the example are doing, and also mention the `OcrEngine::get_text` API.
- Allow the "hello world" example to be run from any directory, by locating models relative to the crate root instead of the current working directory.
- Add `make example` to simplify running the example in development.
=> Improve hello_ocr example

tools/test-e2e.py
When enabled, this causes the actual and expected outputs to be printed in full if there is a mismatch.
=> Add `--verbose` flag to test-e2e.py

js/package.json
npm refuses to publish the package under the name `ocrs` due to similarity to the existing package name `cors`. Take npm's suggestion and scope it under my username.
=> Change package name to avoid name similarity issue

Cargo.lock, ocrs-cli/Cargo.toml, ocrs/Cargo.toml
This fixes a crash on x64 CPUs that don't support AVX2 instructions, and generally improves performance.
Fixes https://github.com/robertknight/ocrs/issues/52
=> Bump rten to v0.8.0

ocrs-cli/Cargo.toml, ocrs/Cargo.toml
This enables the AVX-512 kernels in RTen.
The performance impact on my system is modest (around ~7%). It would be bigger on the server if https://github.com/robertknight/rten/issues/17 was solved.
=> Add `avx512` feature

.github/workflows/ci.yml, Cargo.lock, ocrs-cli/src/main.rs, ocrs-cli/src/output.rs, ocrs/Cargo.toml, ocrs/examples/hello_ocr.rs, ocrs/src/lib.rs, ocrs/src/preprocess.rs, ocrs/src/wasm_api.rs
The steps to load an image were:
1. Load the image into an RGB `image::ImageBuffer`, which holds bytes in channels-last (HWC) layout.
2. Copy image bytes from source into an RGB float tensor in channels-first (CHW) layout with values in [0, 1].
3. Copy values into greyscale CHW float tensor with values in [-0.5, 0.5]
Step (2) is wasteful, especially for large images, and the implementation also unnecessarily allocated zeroed output buffers for steps 2 and 3.
This commit revises the `OcrEngine::prepare_input` API so that it can accept inputs as either floats or bytes, and in either CHW or HWC order. This enables fusing steps 2 and 3 together, avoiding a copy.
For the convenience of the common use case of passing an image loaded using the `image` crate, there is also an …
=> Revise `OcrEngine::prepare_input` API to reduce copies when loading image

ocrs/src/detection.rs, ocrs/src/lib.rs, ocrs/src/tensor_util.rs
Remove a copy that is sometimes redundant:
- If the image doesn't need to be padded, don't copy it
- If the image doesn't need to be resized, don't do an identity resize
For small inputs where both spatial dimensions are smaller than the model's
input we'll need to pad but not resize. For large inputs where the opposite is
true we'll need to resize but not pad. For medium inputs where one dim exceeds
the corresponding model input size and the other is smaller, we'll need to do
both.
=> Avoid unnecessary copies when preparing detection inputs

.github/workflows/ci.yml
The Windows CI build is much slower than Linux. We only need to build and test wasm on one host platform, so do it on Linux. This change was made in the RTen repository previously.
=> Skip WebAssembly on Windows CI

ocrs/src/errors.rs, ocrs/src/lib.rs, ocrs/src/recognition.rs
Complete an old TODO to propagate errors when executing the recognition model.
=> Propagate errors running recognition model, instead of panicking

Makefile, ocrs-cli/Cargo.toml, ocrs-cli/src/models.rs
This provides a more convenient way to test a WebAssembly build of the library compared to the Node demo, with the downside that it isn't the same runtme. Performance seems roughly comparable though.
When running the wasm32-wasi build, models must be loaded from the filesystem, as the infrastructure to download from an HTTPS URL is missing in this platform.
=> Support building CLI for wasm32-wasi

Cargo.lock, Cargo.toml, ocrs-cli/Cargo.toml, ocrs/Cargo.toml, ocrs/src/recognition.rs
The changes include significant performance improvements for the `GRU` operator, which makes recognition of long text lines faster, as well as adapting the thread pool size to the number of physical rather than logical cores, reducing overhead on systems with SMT / hyperthreading.
To adapt to the thread pool changes, `rten::thread_pool().run(...)` is now used to run line recognition preprocessing in the same thread pool that is used to execute the recognition model. This avoids contention from having more threads than cores.
**Benchmarks:**
Testing with the `polar-bears.png` example on an Ice Lake Intel i5:
```
cargo build -r -p ocrs-cli
time target/release/ocrs ocrs-cli/test-data/polar-bears.png
```
Before: ~1.00s
After: ~570ms
In contrast with the `why-rust.png` example, which has a …
=> Bump rten v0.10.0

Cargo.lock, Cargo.toml, ocrs/src/lib.rs, ocrs/src/recognition.rs
Update to latest rten release - [change log](https://github.com/robertknight/rten/blob/main/CHANGELOG.md#0110---2024-07-05).
=> Update to rten v0.11

.github/workflows/ci.yml, Cargo.lock, ocrs/Cargo.toml
This is the same version currently being used by rten.
=> Bump wasm-bindgen-cli to 0.2.92

ocrs-cli/src/main.rs, ocrs/src/lib.rs, ocrs/src/recognition.rs
I made this I don't now if it's good enough to be merged, it just add a parameter with the same default value as before.
=> feat: customizable alphabet using OcrEngineParams

Cargo.lock, Cargo.toml
[CHANGELOG](https://github.com/robertknight/rten/blob/main/CHANGELOG.md#0131---2024-08-30).
=> Bump rten to v0.13.1

ocrs/src/lib.rs
Note when this parameter needs to be set and where to find the default value.
=> Update docs for `OcrEngineParams::alphabet`

ocrs/README.md
This PR, adds small note, letting users know that performance will significantly differ in `build` profile - it could be surprisingly slow (~10x).
=> Add note to README about importance of using `--release` flag when building example

ocrs-cli/src/main.rs
_(Maintainer's note - this is a counterpart to https://github.com/robertknight/ocrs/pull/100 for the CLI tool)_
=> feat: cli can take custom alphabet as args

Makefile, tools/test-e2e.py
This makes it easy to update the expected outputs for E2E tests.
=> Add `update-e2e` make target to update E2E baselines

ocrs-cli/test-data/polar-bears.expected.txt, ocrs/src/recognition.rs
The output of `round_up` was `val + factor` instead of `val` when `val` was an exact multiple of factor. Use the standard library method instead which handles this case correctly. This change resulted in a small change to one of the E2E test outputs.
=> Replace broken `round_up` with `u32::next_multiple_of`

Cargo.lock, Cargo.toml, ocrs/src/detection.rs, ocrs/src/lib.rs
For tensor slicing calls, the rank of the sliced tensor is now inferred and does not need to be specified.
=> Update to rten v0.14

ocrs-cli/src/models.rs, ocrs/src/preprocess.rs, ocrs/src/text_items.rs
Resolve `clippy::needless_lifetimes` lint warnings.
=> Elide lifetimes in impls where possible

.github/workflows/ci.yml, Cargo.lock, Cargo.toml
This release adds support for quantized models, although no quantized versions of the Ocrs default models are available yet.
The rten version ranges are set to ">= 0.14.0, < 0.17.0" since ocrs will build with v0.14.0 or later. There are small semver incompatible changes in the later releases, but they don't affect this library.
=> Bump rten to v0.16

Cargo.lock, ocrs-cli/Cargo.toml, ocrs-cli/src/models.rs
This eliminates a ton of indirect dependencies that came with the latest ureq v2.x version via its `url` dependency (see https://github.com/algesten/ureq/issues/942).
=> Update to ureq v3.x

Cargo.lock, ocrs-cli/Cargo.toml
Update "url" dependency to the current version in ocrs-cli, then disable IDNA support to eliminate 20+ (!) dependencies. Disabling IDNA support uses the mechanism described at https://docs.rs/crate/idna_adapter/latest, which is to pin "idna_adapter" to a specific version.
For reference, ocrs-cli uses the URL dependency only to extract the last path segment from a URL to use as a filename.
=> Update "url" dependency and disable IDNA support

README.md
I was surprised to learn that `cargo install` does not respect a binary package's lockfile by default [^1] and will attempt to upgrade dependencies. Aside from installing package combinations that haven't been directly tested, this also undoes the change in [^2] to avoid installing Unicode-related dependencies. Specifying `--locked` when installing is thus both safer and faster.
[^1]: https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile
[^2]: https://github.com/robertknight/ocrs/pull/163
=> Recommend use of `--locked` when installing ocrs-cli

ocrs/src/text_items.rs
Fix a lint warning during compile when using Rust v1.89 or later.
=> Fix `mismatched_lifetime_syntaxes` lint warning
